### ISSUE TITLE
Error when updating account

### ISSUE THREAD

**Issue by alex6480** [assetgrid/assetgridapp#23]
I tried updating the account for a transaction and received the following error:

Connection id "0HML6UQ8KCRKE", Request id "0HML6UQ8KCRKE:00000002": An unhandled exception was thrown by the application.
assetgrid                |       System.ArgumentNullException: Value cannot be null. (Parameter 'source')
assetgrid                |          at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
assetgrid                |          at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
assetgrid                |          at assetgrid_backend.Controllers.TransactionController.UpdateTransaction(Transaction dbObject, User user, ViewUpdateTransaction model) in /home/runner/work/assetgridapp/assetgridapp/backend/Controllers/TransactionController.cs:line 434
assetgrid                |          at assetgrid_backend.Controllers.TransactionController.Update(Int32 id, ViewUpdateTransaction model) in /home/runner/work/assetgridapp/assetgridapp/backend/Controllers/TransactionController.cs:line 212
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
assetgrid                |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
assetgrid                |          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
assetgrid                |          at assetgrid_backend.Helpers.JwtMiddleware.Invoke(HttpContext context, IUserService userService) in /home/runner/work/assetgridapp/assetgridapp/backend/Helpers/JwtMiddleware.cs:line 29
assetgrid                |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by alex6480** [comment]
Solved
